// Keep all original activities and teacher controls, replace the children's view.
const balloonArt='BALLOON_DATA_URL';
const shortTitles=['Stopdans!','Confetti!','Disco!','Polonaise!','Toveren!','Cadeautje!','De kroon!','Hoepeldans!','Wat is weg?','Zoeken!','Simsala Saartje!','Welke beker?','Bewegen!','Woef, woef!','Samen!','Hooghouden!','Raad maar!','De meester!','Verstoppertje!','Bellen!','Kleurenstopdans!'];
const bigIcons=['🕺','🎊','🪩','🥳','🪄','🎁','👑','⭕','🎁 ❓','🎁 👏','🫧 🐷','🥤 🥤 🥤','🐾','🐶 🎵','🎈 👫','🙌 🎈','🎭','👨‍🏫 ❓','🙈','🫧','🌈 🕺'];
let flights=[],flightFrame,lastTime=performance.now(),queueIndex=0,revealTimer;
const artImage=new Image();artImage.src=balloonArt;
$('celebration').innerHTML='<canvas id="confettiCanvas" aria-hidden="true"></canvas>';
const canvas=$('confettiCanvas'),ctx=canvas.getContext('2d');let particles=[],confettiFrame,lastConfetti=0;
function fitCanvas(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}fitCanvas();window.addEventListener('resize',fitCanvas);
confetti=function(x=innerWidth/2,y=innerHeight*.3){
 const palette=['#f24f91','#ffbd24','#35c8c3','#8762db','#428dea','#ffe18c'];
 for(let i=0;i<220;i++){const rain=i>125;particles.push({x:rain?Math.random()*innerWidth:x,y:rain?-Math.random()*innerHeight*.55:y,vx:rain?(Math.random()-.5)*1.7:(Math.random()-.5)*15,vy:rain?1+Math.random()*2:-2-Math.random()*7,age:0,life:7+Math.random()*3.5,size:5+Math.random()*8,phase:Math.random()*Math.PI*2,spin:Math.random()*6,angle:Math.random()*6,color:palette[i%palette.length]})}
 if(!confettiFrame){lastConfetti=performance.now();confettiFrame=requestAnimationFrame(drawConfetti)}
};
function drawConfetti(now){const dt=Math.min((now-lastConfetti)/1000,.04);lastConfetti=now;ctx.clearRect(0,0,innerWidth,innerHeight);particles=particles.filter(p=>p.age<p.life&&p.y<innerHeight+40);for(const p of particles){p.age+=dt;p.vx*=Math.pow(.986,dt*60);p.vy=Math.min(2.7,p.vy+dt*4);p.x+=(p.vx+Math.sin(p.age*3+p.phase)*1.1)*dt*60;p.y+=p.vy*dt*60;p.angle+=p.spin*dt;ctx.save();ctx.globalAlpha=Math.min(1,(p.life-p.age)*1.5);ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.scale(Math.cos(p.age*5+p.phase)*.7+.3,1);ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.55);ctx.restore()}confettiFrame=particles.length?requestAnimationFrame(drawConfetti):null}
function nextAvailable(exclude=[]){for(let tries=0;tries<activities.length;tries++){const i=queueIndex++%activities.length;if(!used.has(i)&&!exclude.includes(i))return i}return null}
function addFlight(lane,initial=false){const i=nextAvailable(flights.map(f=>f.i));if(i===null)return;const b=document.createElement('button');b.className='balloon';b.dataset.index=i;b.setAttribute('aria-label','Prik ballon '+(i+1));b.style.setProperty('--hue',`${[0,48,165,230,290,330,90][lane%7]}deg`);b.innerHTML=`<img src="${balloonArt}" alt="" draggable="false">`;const depth=[2,0,1,0,2,1,0][lane%7];const scale=.92+Math.random()*.16;const widths=[Math.min(145,Math.max(95,innerWidth*.095)),Math.min(235,Math.max(155,innerWidth*.16)),Math.min(385,Math.max(235,innerWidth*.255))];const width=Math.min(innerWidth*.78,widths[depth]*scale*1.3);b.dataset.depth=depth;b.style.width=width+'px';b.style.height=width*1.5+'px';b.style.zIndex=10+depth;b.style.opacity=[.78,.93,1][depth];$('balloons').append(b);const height=b.offsetHeight;const laneCount=Math.min(7,Math.max(3,Math.floor(innerWidth/175)));const f={i,b,depth,lane:lane%laneCount,y:initial?innerHeight-(lane+.9)*innerHeight/laneCount:innerHeight+40+Math.random()*100,speed:[25,36,48][depth]+Math.random()*6,phase:Math.random()*6,h:height};flights.push(f);positionFlight(f,performance.now()/1000)}
function positionFlight(f,t){const laneCount=Math.min(7,Math.max(3,Math.floor(innerWidth/175)));const laneWidth=innerWidth/laneCount;const x=Math.max(0,Math.min(innerWidth-f.b.offsetWidth,(f.lane+.5)*laneWidth-f.b.offsetWidth/2+Math.sin(t*.6+f.phase)*[12,25,42][f.depth]));f.b.style.transform=`translate3d(${x}px,${f.y}px,0) rotate(${Math.sin(t*.7+f.phase)*5}deg)`}
render=function(){cancelAnimationFrame(flightFrame);flights=[];$('balloons').innerHTML='';const count=Math.min(7,activities.length-used.size,Math.max(3,Math.floor(innerWidth/175)));for(let j=0;j<count;j++)addFlight(j,true);$('status').textContent=`🎈 ${activities.length-used.size} / ${activities.length}`;$('status').setAttribute('aria-label',`${activities.length-used.size} ballonnen over`);$('finish').style.display=used.size===activities.length?'block':'none';$('balloons').style.display='block';$('activityList').innerHTML=activities.map((a,i)=>`<button data-review="${i}">${used.has(i)?'✓':'○'} ${i+1}. ${a[1]}</button>`).join('');lastTime=performance.now();flightFrame=requestAnimationFrame(fly)};
function fly(now){const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;for(const f of [...flights]){f.y-=f.speed*dt;positionFlight(f,now/1000);if(f.y < -f.h-35&&!busy){f.b.remove();flights=flights.filter(x=>x!==f);addFlight(f.lane)}}flightFrame=requestAnimationFrame(fly)}
closeActivity=function(){stopDisco();$('activity').close();for(const f of [...flights]){if(used.has(f.i)){f.b.remove();flights=flights.filter(x=>x!==f);addFlight(f.lane)}}$('status').textContent=`🎈 ${activities.length-used.size} / ${activities.length}`;$('status').setAttribute('aria-label',`${activities.length-used.size} ballonnen over`);$('finish').style.display=used.size===activities.length?'block':'none';$('activityList').innerHTML=activities.map((a,i)=>`<button data-review="${i}">${used.has(i)?'✓':'○'} ${i+1}. ${a[1]}</button>`).join('');$('overviewButton').focus({preventScroll:true})};
$('done').onclick=closeActivity;$('back').onclick=closeActivity;
const originalShow=show;
show=function(i){originalShow(i);$('title').textContent=shortTitles[i];$('icon').textContent=bigIcons[i];let notes=$('teacherNotes');if(!notes){notes=document.createElement('details');notes.id='teacherNotes';notes.innerHTML='<summary>ⓘ Voor de meester</summary><p id="teacherInstruction"></p><p id="teacherHint"></p>';document.querySelector('.slide').append(notes)}notes.open=false;$('teacherInstruction').textContent=activities[i][2];$('teacherHint').textContent=activities[i][3];$('done').textContent='🎈 →';$('done').setAttribute('aria-label','Volgende ballon');$('back').textContent='✕';$('back').setAttribute('aria-label','Terug naar de ballonnen');document.body.classList.remove('revealing');busy=false;if(activities[i][4]==='quiz'){$('special').textContent='🍕  ↔  🥞'};$('actions').querySelectorAll('a').forEach(a=>{const text=a.textContent;a.setAttribute('aria-label',text);a.textContent=i===12?(text.includes('PAW')?'▶ 🐾':'▶ Pokémon'):i===2?'♫ Disco':'▶'});};
$('balloons').onclick=e=>{const b=e.target.closest('button');if(!b||busy||$('activity').open)return;const i=Number(b.dataset.index);if(used.has(i))return;busy=true;const r=b.getBoundingClientRect();document.body.classList.add('revealing');popSound();confetti(r.x+r.width/2,r.y+r.height*.32);b.classList.add('popping');b.disabled=true;used.add(i);save();clearTimeout(revealTimer);revealTimer=setTimeout(()=>show(i),3400)};
// Keep progress and fullscreen available without filling the board with words.
$('sound').textContent=sound?'🔊':'🔇';$('sound').setAttribute('aria-label','Geluid aan of uit');$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'🔊':'🔇';if(!sound)stopMusic()};$('overviewButton').textContent='⚙';$('overviewButton').setAttribute('aria-label','Voor de meester');$('fullscreen').textContent='⛶';$('fullscreen').setAttribute('aria-label','Volledig scherm');document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent='⛶'});
$('finish').querySelector('h2').textContent='Hoera! 🥳';$('finish').querySelector('button').textContent='🎊';
render();
